### ISSUE TITLE
lifetime_emit.rs - index out of bounds

### ISSUE THREAD

**Issue by BLepers** [verus-lang/verus#1035]
Hi all,

Maybe a slightly off-topic request, but I am trying to use Verus to compile and check Linux Rust kernel modules. Does anyone have any experience in doing so?

The kernel launches the following rather complex command, which panics at line `rust_verify/src/lifetime_emit.rs:126`. (I only removed a few -Z and -D options that Verus doesn't support.)

Apologies if the error is out of scope for the project. If no support for verifying the Linux kernel is planned, I'll try to port the Linux interface to something that is compatible with Verus. 

```
$ export RUSTC_BOOTSTRAP=1
$ RUST_BACKTRACE=full RUST_MODFILE=samples/rust_minimal ~/verus/source/target-verus/release/verus -Zbinary_dep_depinfo=y -Dnon_ascii_idents -Dunsafe_op_in_unsafe_fn -Drust_2018_idioms -Wmissing_docs -Drustdoc::missing_crate_level_docs -Dclippy::correctness -Dclippy::style -Dclippy::suspicious -Dclippy::complexity -Dclippy::perf -Dclippy::let_unit_value -Dclippy::mut_mut -Dclippy::needless_bitwise_bool -Dclippy::needless_continue -Wclippy::dbg_macro -Cpanic=abort -Cembed-bitcode=n -Clto=n -Cforce-unwind-tables=n -Ccodegen-units=1 -Csymbol-mangling-version=v0 -Crelocation-model=static -Zfunction-sections=n -Ctarget-feature=-sse,-sse2,-sse3,-ssse3,-sse4.1,-sse4.2,-avx,-avx2 -Zno-jump-tables -Ztune-cpu=generic -Cno-redzone=y -Ccode-model=kernel -Copt-level=2 -Cdebug-assertions=n -Cforce-frame-pointers=y -Cdebuginfo=2 @./include/generated/rustc_cfg -Zcrate-attr=no_std -Zcrate-attr='feature(new_uninit,offset_of)' --extern alloc --extern kernel --crate-type rlib -L ./rust/ --crate-name rust_minimal --out-dir samples/rust/ --emit=dep-info=samples/rust/.rust_minimal.o.d --emit=obj=samples/rust/rust_minimal.o samples/rust/rust_minimal.rs --target=x86_64-unknown-linux-gnu
thread 'rustc' panicked at rust_verify/src/lifetime_emit.rs:126:25:
index out of bounds: the len is 45 but the index is 45
stack backtrace:
   0:     0x7f5ab676349c - std::backtrace_rs::backtrace::libunwind::trace::he43a6a3949163f8c
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f5ab676349c - std::backtrace_rs::backtrace::trace_unsynchronized::h50db52ca99f692e7
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f5ab676349c - std::sys_common::backtrace::_print_fmt::hd37d595f2ceb2d3c
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x7f5ab676349c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h678bbcf9da6d7d75
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f5ab67c93fc - core::fmt::rt::Argument::fmt::h3a159adc080a6fc9
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/fmt/rt.rs:138:9
   5:     0x7f5ab67c93fc - core::fmt::write::hb8eaf5a8e45a738e
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/fmt/mod.rs:1094:21
   6:     0x7f5ab675612e - std::io::Write::write_fmt::h9663fe36b2ee08f9
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/io/mod.rs:1714:15
   7:     0x7f5ab6763284 - std::sys_common::backtrace::_print::hcd4834796ee88ad2
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7f5ab6763284 - std::sys_common::backtrace::print::h1360e9450e4f922a
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7f5ab6766193 - std::panicking::default_hook::{{closure}}::h2609fa95cd5ab1f4
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:270:22
  10:     0x7f5ab6765eac - std::panicking::default_hook::h6d75f5747cab6e8d
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:290:9
  11:     0x7f5ab6766849 - std::panicking::rust_panic_with_hook::h57e78470c47c84de
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:707:13
  12:     0x7f5ab6766747 - std::panicking::begin_panic_handler::{{closure}}::h3dfd2453cf356ecb
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:599:13
  13:     0x7f5ab67639c6 - std::sys_common::backtrace::__rust_end_short_backtrace::hdb177d43678e4d7e
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:170:18
  14:     0x7f5ab6766492 - rust_begin_unwind
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:595:5
  15:     0x7f5ab67c5803 - core::panicking::panic_fmt::hd1e971d8d7c78e0e
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:67:14
  16:     0x7f5ab67c5959 - core::panicking::panic_bounds_check::ha5abdec689e546c1
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:162:5
  17:     0x55746931f38c - rust_verify::lifetime_emit::EmitState::get_pos::h0528bdffdd69e5d6
  18:     0x55746933d381 - rust_verify::lifetime::check_tracked_lifetimes::ha7ebb94f33ad6ae3
  19:     0x5574692e0413 - rustc_middle::ty::context::GlobalCtxt::enter::hff263d767165e364
  20:     0x5574692c89d3 - <rust_verify::verifier::VerifierCallbacksEraseMacro as rustc_driver_impl::Callbacks>::after_expansion::h4e9188a436cff6b0
  21:     0x7f5ab8be1898 - <rustc_interface[5bdd18de9f5858d8]::interface::Compiler>::enter::<rustc_driver_impl[566d207f92c3d9d2]::run_compiler::{closure#1}::{closure#2}, core[d28c4e8d9c4eebaa]::result::Result<core[d28c4e8d9c4eebaa]::option::Option<rustc_interface[5bdd18de9f5858d8]::queries::Linker>, rustc_span[4c9f011e8b033119]::ErrorGuaranteed>>
  22:     0x7f5ab8bdec68 - std[3759e478f3a6c4f2]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[5bdd18de9f5858d8]::util::run_in_thread_pool_with_globals<rustc_interface[5bdd18de9f5858d8]::interface::run_compiler<core[d28c4e8d9c4eebaa]::result::Result<(), rustc_span[4c9f011e8b033119]::ErrorGuaranteed>, rustc_driver_impl[566d207f92c3d9d2]::run_compiler::{closure#1}>::{closure#0}, core[d28c4e8d9c4eebaa]::result::Result<(), rustc_span[4c9f011e8b033119]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[d28c4e8d9c4eebaa]::result::Result<(), rustc_span[4c9f011e8b033119]::ErrorGuaranteed>>
  23:     0x7f5ab8bde3ee - <<std[3759e478f3a6c4f2]::thread::Builder>::spawn_unchecked_<rustc_interface[5bdd18de9f5858d8]::util::run_in_thread_pool_with_globals<rustc_interface[5bdd18de9f5858d8]::interface::run_compiler<core[d28c4e8d9c4eebaa]::result::Result<(), rustc_span[4c9f011e8b033119]::ErrorGuaranteed>, rustc_driver_impl[566d207f92c3d9d2]::run_compiler::{closure#1}>::{closure#0}, core[d28c4e8d9c4eebaa]::result::Result<(), rustc_span[4c9f011e8b033119]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[d28c4e8d9c4eebaa]::result::Result<(), rustc_span[4c9f011e8b033119]::ErrorGuaranteed>>::{closure#1} as core[d28c4e8d9c4eebaa]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  24:     0x7f5ab6771295 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::haadd4e5af2ab0d62
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/alloc/src/boxed.rs:2007:9
  25:     0x7f5ab6771295 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::he4ba1fb09c16d807
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/alloc/src/boxed.rs:2007:9
  26:     0x7f5ab6771295 - std::sys::unix::thread::Thread::new::thread_start::he524ecf4b47bee95
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys/unix/thread.rs:108:17
  27:     0x7f5ab6294ac3 - start_thread
                               at ./nptl/pthread_create.c:442:8
  28:     0x7f5ab6326850 - __GI___clone3
                               at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
  29:                0x0 - <unknown>
```

**Comment by Chris-Hawblitzel** [comment]
I don't think we've tried to run Verus on Linux kernel modules yet.  I took a look at lifetime_emit.rs and there did appear to be a potential bounds violation, and https://github.com/verus-lang/verus/commit/7a63922f5157ba255693bfb93a178e941418c0ad should fix that.  If you still have trouble with lifetime*.rs, you can try shutting it off with the `--no-lifetime` command-line option.

I'd expect that Linux Rust code will use some features that Verus doesn't support yet and therefore can't verify yet.  However, we do try to support having some verified components (inside `verus! { ... }`), using a Verus-supported subset of Rust, interacting with unverified code (outside `verus! { ... }` or in an entirely separate crate) using full Rust.  One example of this is https://github.com/microsoft/verified-storage .  If Verus is failing to process the unverified code, then that's something we'd like to fix.  Let us know if there's any way we can help with this.

**Comment by BLepers** [comment]
Thanks, the patch seems to fix the issue. I still have compilation errors, but I will try to fix them before opening another issue.

Related to your last point. Maybe of interest if verus is supposed to support all Rust code outside the `verus!{}` block:

```
verus --crate-type rlib -L./rust /home/ubuntu/.rustup/toolchains/1.73.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/lib.rs 
[rust_verify/src/rust_to_vir_base.rs:910]
error: The verifier does not yet support the following Rust feature: floating point types
  --> /home/ubuntu/.rustup/toolchains/1.73.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/num/f32.rs:93:1
   |
93 | pub const EPSILON: f32 = f32::EPSILON;
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error
```

(The file doesn't contain any verus block or verus-related code.)

**Comment by tjhance** [comment]
By coincidence, I just now fixed the issue with the floating point types. If you update again, I expect this should be fixed.

**Comment by BLepers** [comment]
Indeed! Thanks for the update, I'll close the issue.
