### ISSUE TITLE
panic at rust_verify/src/rust_to_vir_base.rs

### ISSUE THREAD

**Issue by clemsys** [verus-lang/verus#1064]
Hi all,

I am currently trying to use Verus to compile and check Linux Rust kernel modules. I encountered a panic while running Verus on the rnull driver (`drivers/block/rnull.rs`) from [metaspace:rnull-6.7](https://github.com/metaspace/linux/tree/rnull-6.7)

When building this file, `make` eventually runs the following command (I only removed a few -Z and -D options):
```
$ export RUSTC_BOOTSTRAP=1
$ RUST_MODFILE=drivers/block/rnull rustc --edition=2021 @./include/generated/rustc_cfg \
    -Drust_2018_idioms -Zallow-features=new_uninit,offset_of,allocator_api,impl_trait_in_assoc_type \
    -Zcrate-attr='feature(new_uninit,offset_of,allocator_api,impl_trait_in_assoc_type)' --extern alloc \
    --extern kernel --crate-type rlib -L ./rust/ --crate-name rnull --out-dir drivers/block/ \
    --emit=dep-info=drivers/block/.rnull.o.d --emit=obj=drivers/block/rnull.o drivers/block/rnull.rs
```
I only kept the `-Z` flags which are absolutely necessary for the file to compile (they enable some nightly features).

**Without even adding a `verus!` block**, I tried to verify this file using the following command (I just replaced `rustc` by `verus` in the command above):
```
$ RUST_MODFILE=drivers/block/rnull.rs <path-to-verus> @./include/generated/rustc_cfg \
    -Zallow-features=new_uninit,offset_of,allocator_api,impl_trait_in_assoc_type \
    -Zcrate-attr='feature(new_uninit,offset_of,allocator_api,impl_trait_in_assoc_type)' \
    --extern alloc --extern kernel --crate-type rlib -L ./rust/ --crate-name rnull --out-dir drivers/block \
    --emit=dep-info=drivers/block/.rnull.o.d --emit=obj=drivers/block/rnull.o drivers/block/rnull.rs
```
and got the following errors
```
error[E0725]: the feature `stmt_expr_attributes` is not in the list of allowed features
 --> <crate attribute>:1:9
  |
1 | feature(stmt_expr_attributes)
  |         ^^^^^^^^^^^^^^^^^^^^

error[E0725]: the feature `box_patterns` is not in the list of allowed features
 --> <crate attribute>:1:9
  |
1 | feature(box_patterns)
  |         ^^^^^^^^^^^^

[...]
```

I then tried to remove the `-Z` flags that enable some nightly features.
```
$ RUST_MODFILE=drivers/block/rnull.rs <path-to-verus> @./include/generated/rustc_cfg --extern alloc \
    --extern kernel --crate-type rlib -L ./rust/ --crate-name rnull --out-dir drivers/block \
    --emit=dep-info=drivers/block/.rnull.o.d --emit=obj=drivers/block/rnull.o drivers/block/rnull.rs
```
and got the following error
```
error[E0658]: use of unstable library feature 'offset_of'
   --> drivers/block/rnull.rs:210:1
    |
210 | / kernel::impl_has_timer! {
211 | |     impl HasTimer<Self> for Pdu { self.timer }
212 | | }
    | |_^
    |
    = note: see issue #106655 <https://github.com/rust-lang/rust/issues/106655> for more information
    = help: add `#![feature(offset_of)]` to the crate attributes to enable
    = note: this error originates in the macro `kernel::impl_has_timer` (in Nightly builds, run with -Z macro-backtrace for more info)
```

I then followed the suggestions from the error message, adding attributes at the top of my file until Verus stopped suggesting me to do so 
```
#![feature(offset_of)]
#![feature(allocator_api)]
#![feature(impl_trait_in_assoc_type)]
``` 
After rerunning Verus, I ended up getting a panic:
```
thread 'rustc' panicked at rust_verify/src/rust_to_vir_base.rs:154:28:
unhandled name DefId(0:158 ~ rnull[311a]::add_disk::{closure#0}::__InitOk)
stack backtrace:
   0:     0x7f55e5db66f6 - std::backtrace_rs::backtrace::libunwind::trace::hbee8a7973eeb6c93
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x7f55e5db66f6 - std::backtrace_rs::backtrace::trace_unsynchronized::hc8ac75eea3aa6899
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f55e5db66f6 - std::sys_common::backtrace::_print_fmt::hc7f3e3b5298b1083
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x7f55e5db66f6 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hbb235daedd7c6190
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f55e5e08f40 - core::fmt::rt::Argument::fmt::h76c38a80d925a410
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/fmt/rt.rs:142:9
   5:     0x7f55e5e08f40 - core::fmt::write::h3ed6aeaa977c8e45
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/fmt/mod.rs:1120:17
   6:     0x7f55e5daa53f - std::io::Write::write_fmt::h78b18af5775fedb5
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/io/mod.rs:1810:15
   7:     0x7f55e5db64d4 - std::sys_common::backtrace::_print::h5d645a07e0fcfdbb
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7f55e5db64d4 - std::sys_common::backtrace::print::h85035a511aafe7a8
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7f55e5db9267 - std::panicking::default_hook::{{closure}}::hcce8cea212785a25
  10:     0x7f55e5db8fc9 - std::panicking::default_hook::hf5fcb0f213fe709a
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:292:9
  11:     0x7f55e5db9828 - std::panicking::rust_panic_with_hook::h095fccf1dc9379ee
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:779:13
  12:     0x7f55e5db9702 - std::panicking::begin_panic_handler::{{closure}}::h032ba12139b353db
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:657:13
  13:     0x7f55e5db6bf6 - std::sys_common::backtrace::__rust_end_short_backtrace::h9259bc2ff8fd0f76
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:171:18
  14:     0x7f55e5db9460 - rust_begin_unwind
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
  15:     0x7f55e5e05645 - core::panicking::panic_fmt::h784f20a50eaab275
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
  16:     0x562f53e9f8f7 - rust_verify::rust_to_vir_base::def_id_to_vir_path::h3caef56d9d863069
  17:     0x562f53da276b - rust_verify::rust_to_vir::check_item::h46516ae08cb5cc00
  18:     0x562f53da90b9 - rust_verify::rust_to_vir::crate_to_vir::hf7e107487f543039
  19:     0x562f53e2554c - rust_verify::verifier::Verifier::construct_vir_crate::hc9c6a87369536c95
  20:     0x562f53df3bf0 - rustc_middle::ty::context::GlobalCtxt::enter::h5ab9270d552770ea
  21:     0x562f53e28df5 - <rust_verify::verifier::VerifierCallbacksEraseMacro as rustc_driver_impl::Callbacks>::after_expansion::h486666fd3d17e265
  22:     0x7f55e4afe63a - rustc_interface[bf5cafa581ab7832]::interface::run_compiler::<core[f975038e3cc9791c]::result::Result<(), rustc_span[7a149c27976a99e7]::ErrorGuaranteed>, rustc_driver_impl[66ed8fdbde15dc6c]::run_compiler::{closure#0}>::{closure#0}
  23:     0x7f55e4c2c7db - std[79729d9c385e1623]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[bf5cafa581ab7832]::util::run_in_thread_with_globals<rustc_interface[bf5cafa581ab7832]::interface::run_compiler<core[f975038e3cc9791c]::result::Result<(), rustc_span[7a149c27976a99e7]::ErrorGuaranteed>, rustc_driver_impl[66ed8fdbde15dc6c]::run_compiler::{closure#0}>::{closure#0}, core[f975038e3cc9791c]::result::Result<(), rustc_span[7a149c27976a99e7]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[f975038e3cc9791c]::result::Result<(), rustc_span[7a149c27976a99e7]::ErrorGuaranteed>>
  24:     0x7f55e4c2c639 - <<std[79729d9c385e1623]::thread::Builder>::spawn_unchecked_<rustc_interface[bf5cafa581ab7832]::util::run_in_thread_with_globals<rustc_interface[bf5cafa581ab7832]::interface::run_compiler<core[f975038e3cc9791c]::result::Result<(), rustc_span[7a149c27976a99e7]::ErrorGuaranteed>, rustc_driver_impl[66ed8fdbde15dc6c]::run_compiler::{closure#0}>::{closure#0}, core[f975038e3cc9791c]::result::Result<(), rustc_span[7a149c27976a99e7]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[f975038e3cc9791c]::result::Result<(), rustc_span[7a149c27976a99e7]::ErrorGuaranteed>>::{closure#1} as core[f975038e3cc9791c]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  25:     0x7f55e5dc38e5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h12de4fc57affb195
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/alloc/src/boxed.rs:2015:9
  26:     0x7f55e5dc38e5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h3c619f45059d5cf1
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/alloc/src/boxed.rs:2015:9
  27:     0x7f55e5dc38e5 - std::sys::unix::thread::Thread::new::thread_start::hbac657605e4b7389
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys/unix/thread.rs:108:17
  28:     0x7f55dfeac897 - start_thread
  29:     0x7f55dff33a5c - __clone3
  30:                0x0 - <unknown>
```

I don't really understand what could cause such an issue. Maybe the above mentioned nightly features are not supported by verus ? It also seems odd to me that enabling the nightly features with the `-Z` flags or using `#![]` attributes at the top of my file give different results.

If you have any idea about what might be causing my problem or where I could look to find out more, I would be glad to know!

**Comment by tjhance** [comment]
The key line is this one: `unhandled name DefId(0:158 ~ rnull[311a]::add_disk::{closure#0}::__InitOk)`

It looks like __InitOk (which appears to be declared from a macro expansion inside `add_disk`) is a nested item. Verus doesn't support nested items. Normally, it ought to be OK anyway because you haven't asked Verus to verify `add_disk`, so I think this must be a Verus bug.

**Comment by clemsys** [comment]
Thank you very much! I'll try to get around the problem for now. If you need to reproduce the bug, feel free to ask. I'll be glad to provide detailed reproducible instructions!

**Comment by tjhance** [comment]
By the way, what commit of Verus are you using? I ask because I fixed a related bug just a couple of weeks ago, so I wonder if the issue is that you have an older Verus.

**Comment by clemsys** [comment]
I am using the commit `bd46b8dcaf5e5a72ca0fefb965b61e4ddbdb5030` (branch `main`, Apr 7, 2024)

**Comment by clemsys** [comment]
I just managed to get around my problem by adding the line
```
            DefPathData::Closure => {}
```
in the function `def_path_to_vir_path` from `rust_verify/src/rust_to_vir_base.rs`
```
fn def_path_to_vir_path<'tcx>(tcx: TyCtxt<'tcx>, def_path: DefPath) -> Option<Path> {
    let multi_crate = MULTI_CRATE.with(|m| m.load(std::sync::atomic::Ordering::Relaxed));
    let krate = if def_path.krate == LOCAL_CRATE && !multi_crate {
        None
    } else {
        Some(Arc::new(tcx.crate_name(def_path.krate).to_string()))
    };
    let mut segments: Vec<vir::ast::Ident> = Vec::new();
    for d in def_path.data.iter() {
        use rustc_hir::definitions::DefPathData;
        match &d.data {
            DefPathData::ValueNs(symbol) | DefPathData::TypeNs(symbol) => {
                segments.push(Arc::new(symbol.to_string()));
            }
            DefPathData::Ctor => {
                segments.push(Arc::new(vir::def::RUST_DEF_CTOR.to_string()));
            }
            DefPathData::Impl => {
                segments.push(vir::def::impl_ident(d.disambiguator));
            }
            DefPathData::ForeignMod => {
                // this segment can be ignored
            }
            DefPathData::Closure => {}
            _ => return None,
        }
    }
    Some(Arc::new(PathX { krate, segments: Arc::new(segments) }))
}
```

I realized that when running Verus without a `verus` block on my file, `d.data` is a `DefPathData::Closure` at some point, which causes Verus to panic without the line I added.

I don't know if its a viable solution to my bug. I'd be glad to provide additional information. Thanks for your help!

**Comment by Chris-Hawblitzel** [comment]
Thanks for finding the root of this problem.  I think I now understand what's going on based on the information you've provided.  I believe we should not be calling `def_path_to_vir_path` at all for external items that might cause `def_path_to_vir_path` to panic.  Can you try out pull request https://github.com/verus-lang/verus/pull/1074 to see if it solves the issue?

**Comment by clemsys** [comment]
I tried out your PR and it indeed solves the issue! Thank you so much!
