### ISSUE TITLE
Panic with expand-errors + overflow checks

### ISSUE THREAD

**Issue by jaybosamiya-ms** [verus-lang/verus#1214]
Minimized input:
```rs
use vstd::prelude::*;
verus! {

fn a(b: i32) -> i32 {
    let c = 0;
    while c + 1 <= b {
    }
    c
}

} // verus!
fn main() {}
```

Panics when run with `--expand-errors`:

```console
$ verus foo.rs --expand-errors
thread '<unnamed>' panicked at vir/src/expand_errors.rs:90:9:
get_expansion_ctx: did not find the given assert_id
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at rust_verify/src/verifier.rs:350:17:
dropped, expected call to `into_inner` instead
stack backtrace:
   0:     0x7f153798b6f6 - std::backtrace_rs::backtrace::libunwind::trace::hbee8a7973eeb6c93
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x7f153798b6f6 - std::backtrace_rs::backtrace::trace_unsynchronized::hc8ac75eea3aa6899
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f153798b6f6 - std::sys_common::backtrace::_print_fmt::hc7f3e3b5298b1083
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x7f153798b6f6 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hbb235daedd7c6190
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f15379ddf40 - core::fmt::rt::Argument::fmt::h76c38a80d925a410
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/fmt/rt.rs:142:9
   5:     0x7f15379ddf40 - core::fmt::write::h3ed6aeaa977c8e45
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/fmt/mod.rs:1120:17
   6:     0x7f153797f53f - std::io::Write::write_fmt::h78b18af5775fedb5
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/io/mod.rs:1810:15
   7:     0x7f153798b4d4 - std::sys_common::backtrace::_print::h5d645a07e0fcfdbb
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7f153798b4d4 - std::sys_common::backtrace::print::h85035a511aafe7a8
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7f153798e267 - std::panicking::default_hook::{{closure}}::hcce8cea212785a25
  10:     0x7f153798dfc9 - std::panicking::default_hook::hf5fcb0f213fe709a
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:292:9
  11:     0x7f153798e828 - std::panicking::rust_panic_with_hook::h095fccf1dc9379ee
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:779:13
  12:     0x5624488b610d - std::panicking::begin_panic::{{closure}}::h7d943025b9aab28a
  13:     0x5624488b3ca6 - std::sys_common::backtrace::__rust_end_short_backtrace::hbe36db03c1754811
  14:     0x562448677a3a - std::panicking::begin_panic::h7ede8bd9c91d2094
  15:     0x5624486fcd26 - core::ptr::drop_in_place<core::option::Option<rust_verify::verifier::util::PanicOnDropVec<(alloc::sync::Arc<vir::messages::MessageX>,air::messages::MessageLevel)>>>::hbd7d395a3f6460ac
  16:     0x562448716cf9 - rust_verify::verifier::Verifier::verify_bucket::h94e96a1e525b4a23
  17:     0x5624486f9745 - std::panicking::try::ha7a83530c5046b0b
  18:     0x5624488b3d1b - std::sys_common::backtrace::__rust_begin_short_backtrace::hce76a7518fb33635
  19:     0x56244875ea7f - core::ops::function::FnOnce::call_once{{vtable.shim}}::h503e3dfd269a0f72
  20:     0x7f15379988e5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h12de4fc57affb195
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/alloc/src/boxed.rs:2015:9
  21:     0x7f15379988e5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h3c619f45059d5cf1
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/alloc/src/boxed.rs:2015:9
  22:     0x7f15379988e5 - std::sys::unix::thread::Thread::new::thread_start::hbac657605e4b7389
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys/unix/thread.rs:108:17
  23:     0x7f153765eac3 - <unknown>
  24:     0x7f15376f0850 - <unknown>
  25:                0x0 - <unknown>
thread '<unnamed>' panicked at library/core/src/panicking.rs:163:5:
panic in a destructor during cleanup
thread caused non-unwinding panic. aborting.
[1]    772326 IOT instruction  verus foo.rs --expand-errors
```

---

Tested on
```console
$ verus --version
Verus
  Version: 0.2024.07.08.d52a17f
  Profile: release
  Platform: linux_x86_64
  Toolchain: 1.76.0-x86_64-unknown-linux-gnu
```

**Comment by jaybosamiya-ms** [comment]
Thanks for the quick fix @tjhance!
