### ISSUE TITLE
thread 'rustc' panicked at vir/src/traits.rs:377:58

### ISSUE THREAD

**Issue by BLepers** [verus-lang/verus#1261]
Commit version: 9e6c6b917399250dd3ac292f7dbc6c3c944e90b1 (9 Sep 2024)

Command:
```
export RUSTC_BOOTSTRAP=1;
./verus/source/target-verus/release/verus --crate-name binder foo.rs --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 -C metadata=de5cff490500dacc -C extra-filename=-de5cff490500dacc --extern macros=./libmacros-6c6abace889deed9.so
```

Files (not minimal, but triggers the error):
[foo.zip](https://github.com/user-attachments/files/16943026/foo.zip)

Error:
```
thread 'rustc' panicked at vir/src/traits.rs:377:58
```

It is possible that the code contains multiple unsupported features, but I guess the crash is unexpected. Any idea?

The panic occurs when trying to put the following code in a verus! block:

```
pub trait IoBufferReader {
    /// Returns the number of bytes left to be read from the io buffer.
    ///
    /// Note that even reading less than this number of bytes may fail.
    fn len(&self) -> usize;

    /// Returns `true` if no data is available in the io buffer.
    fn is_empty(&self) -> bool {
        self.len() == 0
    }

    /// Reads raw data from the io buffer into a raw kernel buffer.
    ///
    /// # Safety
    ///
    /// The output buffer must be valid.
    fn read_raw(&mut self, out: *mut u8, len: usize) -> Result;

    /// Reads all data remaining in the io buffer.
    ///
    /// Returns `EFAULT` if the address does not currently point to mapped, readable memory.
    fn read_all(&mut self) -> Result<Vec<u8>> {
        let mut data = Vec::<u8>::new();
        data.resize(self.len(), 0);

        // SAFETY: The output buffer is valid as we just allocated it.
        unsafe { self.read_raw(data.as_mut_ptr(), data.len())? };
        Ok(data)
    }

    /// Reads a byte slice from the io buffer.
    ///
    /// Returns `EFAULT` if the byte slice is bigger than the remaining size of the user slice or
    /// if the address does not currently point to mapped, readable memory.
    fn read_slice(&mut self, data: &mut [u8]) -> Result {
        // SAFETY: The output buffer is valid as it's coming from a live reference.
        unsafe { self.read_raw(data.as_mut_ptr(), data.len()) }
    }

    /// Reads the contents of a plain old data (POD) type from the io buffer.
    fn read<T: ReadableFromBytes>(&mut self) -> Result<T> {
        let mut out = MaybeUninit::<T>::uninit();
        // SAFETY: The buffer is valid as it was just allocated.
        unsafe { self.read_raw(out.as_mut_ptr() as _, size_of::<T>()) }?;
        // SAFETY: We just initialised the data.
        Ok(unsafe { out.assume_init() })
    }
}
```

**Comment by tjhance** [comment]
I haven't been able to reproduce. Trying to use the zip file, I encountered a problem with the `.so` file. I haven't been able to work with the included code snippet either. It seems malformed; the name `Result` is used inconsistently (`read_raw` returns `Result` while `read` returns `Result<T>`; I don't see how both of these can be well-typed at the same time).

**Comment by tjhance** [comment]
I couldn't get the zip file to work (had problems with the .so) file, so I attempted to minimize as follows:

```
verus!{

struct Error { }

pub unsafe trait ReadableFromBytes { }

pub type Result<T = ()> = core::result::Result<T, Error>;

pub trait IoBufferReader {
    /// Returns the number of bytes left to be read from the io buffer.
    ///
    /// Note that even reading less than this number of bytes may fail.
    fn len(&self) -> usize;

    /// Returns `true` if no data is available in the io buffer.
    fn is_empty(&self) -> bool {
        self.len() == 0
    }

    /// Reads raw data from the io buffer into a raw kernel buffer.
    ///
    /// # Safety
    ///
    /// The output buffer must be valid.
    fn read_raw(&mut self, out: *mut u8, len: usize) -> Result;

    /// Reads all data remaining in the io buffer.
    ///
    /// Returns `EFAULT` if the address does not currently point to mapped, readable memory.
    fn read_all(&mut self) -> Result<Vec<u8>> {
        let mut data = Vec::<u8>::new();
        data.resize(self.len(), 0);

        // SAFETY: The output buffer is valid as we just allocated it.
        unsafe { self.read_raw(data.as_mut_ptr(), data.len())? };
        Ok(data)
    }

    /// Reads a byte slice from the io buffer.
    ///
    /// Returns `EFAULT` if the byte slice is bigger than the remaining size of the user slice or
    /// if the address does not currently point to mapped, readable memory.
    fn read_slice(&mut self, data: &mut [u8]) -> Result {
        // SAFETY: The output buffer is valid as it's coming from a live reference.
        unsafe { self.read_raw(data.as_mut_ptr(), data.len()) }
    }

    /// Reads the contents of a plain old data (POD) type from the io buffer.
    fn read<T: ReadableFromBytes>(&mut self) -> Result<T> {
        let mut out = MaybeUninit::<T>::uninit();
        // SAFETY: The buffer is valid as it was just allocated.
        unsafe { self.read_raw(out.as_mut_ptr() as _, size_of::<T>()) }?;
        // SAFETY: We just initialised the data.
        Ok(unsafe { out.assume_init() })
    }
}

}
```

this results in the expect error message `alloc::vec::impl&%1::as_mut_ptr` is not supported`.

Kind of an old issue now, so it's not clear if the panic still exists. I'm going to close this, but feel free to reopen (or start a new issue) with more specific repro instructions.
