### ISSUE TITLE
thread 'rustc' panicked at rust_verify/src/rust_to_vir_func.rs:1538:59: impl_of_method

### ISSUE THREAD

**Issue by BLepers** [verus-lang/verus#1262]
Slight variation of https://github.com/verus-lang/verus/issues/1261 triggers a different panic.

Commit 9e6c6b917399250dd3ac292f7dbc6c3c944e90b1

Command:

```
export RUSTC_BOOTSTRAP=1;
./verus/source/target-verus/release/verus --crate-name binder foo.rs --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 -C metadata=de5cff490500dacc -C extra-filename=-de5cff490500dacc --extern macros=./libmacros-6c6abace889deed9.so
```

Files (not minimal, but triggers the error):
[foo.zip](https://github.com/user-attachments/files/16943412/foo.zip)

Error:
```
thread 'rustc' panicked at rust_verify/src/rust_to_vir_func.rs:1538:59:
impl_of_method
```

Any idea? :)

**Comment by tjhance** [comment]
This error occurs when external_fn_specification is used to specify a function for a method of a trait impl that uses the default method implementation. Here's a minimal example:

```rust
use vstd::prelude::*;

pub trait Tr {
    fn foo(&self) -> bool { true }
}

pub struct X { } 

impl Tr for X { 
}

verus!{
    #[verifier(external_type_specification)]
    pub struct ExX(X);

    #[verifier(external_fn_specification)]
    pub fn ex_X_foo(p: &X) -> bool {
        p.foo()
    }   
}

fn main() { } 
```
