### ISSUE TITLE
thread '<unnamed>' panicked at rust_verify/src/verifier.rs:780:21 (generated ill-typed AIR code)

### ISSUE THREAD

**Issue by BLepers** [verus-lang/verus#1263]
Commit 922601390aa51b8fb241f846bc884489c5adef5d

Error:
```
thread '<unnamed>' panicked at rust_verify/src/verifier.rs:780:21:
internal error: generated ill-typed AIR code: error 'in call to binder!bindings.bindings_generated.file./file/private_data, argument #1 has type "ptr_mut%<binder!bindings.bindings_generated.file.>." when it should have type "binder!bindings.bindings_generated.file."' in expression '(binder!bindings.bindings_generated.file./file/private_data (%Poly%ptr_mut%<binder!bindings.bindings_generated.file.>.
  (Poly%ptr_mut%<binder!bindings.bindings_generated.file.>. file!)
))'
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at rust_verify/src/verifier.rs:2108:29:
worker thread panicked
thread '<unnamed>' panicked at rust_verify/src/verifier.rs:182:64:
could not send!: SendError { .. }
thread '<unnamed>' panicked at rust_verify/src/verifier.rs:2107:34:
mpsc open: SendError { .. }
thread '<unnamed>' panicked at rust_verify/src/verifier.rs:182:64:
could not send!: SendError { .. }
thread '<unnamed>' panicked at rust_verify/src/verifier.rs:2107:34:
mpsc open: SendError { .. }
```

From the error, my guess is that the problem comes from the following lines/functions:

```
# Also crashes without the cast
let f = unsafe { crate::kernel::types::borrow_verus((*file).private_data as *const core::ffi::c_void) };


#[repr(C)]
#[derive(Copy, Clone)]
pub struct file {
    pub private_data: *mut core::ffi::c_void,
}

pub fn borrow_verus<'a, T>(ptr: *const core::ffi::c_void) -> RefBorrow<'a, T> {
    // SAFETY: The safety requirements for this function ensure that the underlying object
    // remains valid for the lifetime of the returned value.
    unsafe { Ref::borrow_usize(ptr as _) }
}

verus!{
#[verifier(external_fn_specification)]
pub fn ex_ref_borrow<'a, T> (ptr: *const core::ffi::c_void) -> RefBorrow<'a, T> {
    crate::kernel::types::borrow_verus(ptr)
}
}
```

To reproduce:
```
/verus/source/target-verus/release/verus --crate-name binder foo.rs --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 -C metadata=de5cff490500dacc -C extra-filename=-de5cff490500dacc --extern macros=./libmacros-6c6abace889deed9.so
```

With the following files:
[foo.zip](https://github.com/user-attachments/files/16963884/foo.zip)

Any idea?

**Comment by tjhance** [comment]
What's the type of `file`? I'm guessing it's a `*mut file` or `*const file`?

Dereferencing a pointer is unsafe, so it's only supported via Verus's pointer-permission interface. A "normal" Rust dereference like `*file` is unsupported. 

So the error message here should be something like:

```
let f = unsafe { crate::kernel::types::borrow_verus((*file).private_data as *const core::ffi::c_void) };
                                                     ^^^^^ dereference of raw pointer not supported
```

**Comment by BLepers** [comment]
Thanks for the explanation. Indeed, file is a `*mut file`. I'll try to switch to the raw_ptr interface.

**Comment by tjhance** [comment]
I've added what's hopefully a clearer error message for this.
