### ISSUE TITLE
external_body in trait causes a panic

### ISSUE THREAD

**Issue by emugnier** [verus-lang/verus#1268]
The following [code](https://play.verus-lang.org/?version=stable&mode=basic&edition=2021&gist=3dea38167679b7dacb96ba5911ff072f) causes a panic:

```rust
use vstd::prelude::verus;

verus! {

    pub trait A {
    
        #[verifier(external_body)]
        fn external_body_func() -> u32 {
            let nb1: u32 = 64;
            let nb2: u32 = 32;
            nb1.saturating_sub(nb2)
        }
        
    }
}
```

```
thread 'rustc' panicked at rust_verify/src/lifetime_generate.rs:1671:38:
no entry found for key
stack backtrace:
   0: rust_begin_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
   2: core::panicking::panic_display
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:196:5
   3: core::panicking::panic_str
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:171:5
   4: core::option::expect_failed
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/option.rs:1980:5
   5: rust_verify::lifetime_generate::erase_stmt
   6: rust_verify::lifetime_generate::erase_block
   7: rust_verify::lifetime_generate::erase_expr
   8: rust_verify::lifetime_generate::erase_fn_common
   9: rust_verify::lifetime_generate::erase_trait_item
  10: rust_verify::lifetime_generate::gen_check_tracked_lifetimes
  11: rust_verify::lifetime::check_tracked_lifetimes
  12: rustc_middle::ty::context::GlobalCtxt::enter
  13: <rust_verify::verifier::VerifierCallbacksEraseMacro as rustc_driver_impl::Callbacks>::after_expansion
  14: rustc_interface::interface::run_compiler::<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#0}>::{closure#0}
```

[example.zip](https://github.com/user-attachments/files/17021298/example.zip)

**Comment by tjhance** [comment]
fixed in f833b121bc677b0b1a68c82d002bcbbbf96b2a7e
