### ISSUE TITLE
Verus panics on `assert_seqs_equal!` after #1289

### ISSUE THREAD

**Issue by pratapsingh1729** [verus-lang/verus#1291]
I have some code that includes an `assert_seqs_equal!` macro call. Here is a [playground link](https://play.verus-lang.org/?version=stable&mode=basic&edition=2021&gist=6b54581764fd6e822b94f557e863c002). The example below is minimized from a larger example using the automated minimizer, so the proof is not expected to verify---the problem is the panic, not the proof failure.
```
use vstd::{prelude::*, *};
verus! {

enum Foo<'a> {
    Foo(&'a [u8]),
}

impl View for Foo<'_> {
    type V = Seq<u8>;

    open spec fn view(&self) -> Self::V;
}

impl<'d> Foo<'d> {
    fn len(&self) -> usize {
        match self {
            Foo::Foo(e) => {
                // NB: This is expected to not verify, since this 
                // is a minimized example
                proof {
                    assert_seqs_equal!(e.view(), self.view());
                }
                slice_len(e)
            },
        }
    }
}

fn slice_len(i: &[u8]) -> usize {
    i.len()
}

} // verus!
fn main() {}
```

When I run Verus I get the panic:
```
thread '<unnamed>' panicked at rust_verify/src/verifier.rs:780:21:
internal error: generated ill-typed AIR code: error 'in equality, left expression has type vstd!seq.Seq<u8.>. and right expression has different type Poly' in expression '(= s1@ (vstd!view.View.view.? $ (SLICE $ (UINT 8)) (Poly%slice%<u8.>. s@)))'
note: [run with `RUST_BACKTRACE=1` environment variable to display a backtrace](https://play.verus-lang.org/?version=stable&mode=basic&edition=2021#)
thread '<unnamed>' panicked at rust_verify/src/verifier.rs:2110:29:
worker thread panicked
```

If I comment out `proof { assert_seqs_equal!(e.view(), self.view()); }`, the panic disappears and Verus handles this code just fine.

Interestingly, if I roll back #1289, the panic also disappears (this time I get a proof failure on the `assert_seqs_equal!`, as expected). This, combined with the "ill-typed AIR code" message mentioning a type difference between `Seq<u8>` and `Poly`, makes me suspect that the poly refactor might have broken this example.

**Comment by pratapsingh1729** [comment]
Yes, with Verus version
```
Verus
  Version: 0.2024.10.11.dba7a12
  Profile: release
  Platform: linux_x86_64
  Toolchain: 1.76.0-x86_64-unknown-linux-gnu
```
my larger example works. Thanks for fixing!
