### ISSUE TITLE
Panic when implementing View for lifetime tagged enums: internal error: ill-typed AIR code 

### ISSUE THREAD

**Issue by y1ca1** [verus-lang/verus#1303]
The following code panics:
 ```rust
pub type SpecBytes = Seq<u8>;

pub type Bytes<'a> = &'a [u8];

pub enum SpecMsg {
    M0(SpecBytes),
}

pub enum Msg<'a> {
    M0(Bytes<'a>),
}

impl View for Msg<'_> {
    type V = SpecMsg;

    open spec fn view(&self) -> Self::V {
        match self {
            Msg::M0(m) => SpecMsg::M0(m@),
        }
    }
}
```
---
```sh
thread '<unnamed>' panicked at rust_verify/src/verifier.rs:552:17:
internal error: ill-typed AIR code: error 'error 'error 'in call to main!SpecMsg./M0, argument #1 has type "Poly" when it should have type "vstd!seq.Seq<u8.>."' in expression '(main!SpecMsg./M0 (vstd!view.View.view.? $ (SLICE $ (UINT 8)) (Poly%slice%<u8.>. m$)))'' in expression '(Poly%main!SpecMsg. (let
  ((m$ (main!Msg./M0/0 (%Poly%main!Msg. self!))))
  (main!SpecMsg./M0 (vstd!view.View.view.? $ (SLICE $ (UINT 8)) (Poly%slice%<u8.>. m$)))
))'' in expression '(=>
 (fuel_bool fuel%main!impl&%3.view.)
 (forall ((self! Poly)) (!
   (= (vstd!view.View.view.? $ TYPE%main!Msg. self!) (Poly%main!SpecMsg. (let
      ((m$ (main!Msg./M0/0 (%Poly%main!Msg. self!))))
      (main!SpecMsg./M0 (vstd!view.View.view.? $ (SLICE $ (UINT 8)) (Poly%slice%<u8.>. m$)))
   )))
   :pattern ((vstd!view.View.view.? $ TYPE%main!Msg. self!))
   :qid internal_vstd!view.View.view.?_definition
   :skolemid skolem_internal_vstd!view.View.view.?_definition
)))'
note: [run with `RUST_BACKTRACE=1` environment variable to display a backtrace](https://play.verus-lang.org/#)
thread '<unnamed>' panicked at rust_verify/src/verifier.rs:2110:29:
worker thread panicked
```

But the following (for lifetime tagged structs) is ok:
```rust
pub struct MsgStruct<'a>(pub Bytes<'a>);

impl View for MsgStruct<'_> {
    type V = SpecMsg;

    open spec fn view(&self) -> Self::V {
        SpecMsg::M0(self.0@)
    }
}
```

[Link to Verus Playground](https://play.verus-lang.org/?version=stable&mode=basic&edition=2021&gist=d998fd1dae6eb20e285996afa1d6cc61)

I haven't tried to pinpoint the bug, but I at least with the commit a3c257e717b7b6166ec14cb3580668fe9726c998, it didn't panic.

**Comment by Chris-Hawblitzel** [comment]
Can you try the `main` branch now?

**Comment by y1ca1** [comment]
The panic goes away. Thanks!
