### ISSUE TITLE
panic related to error expansion

### ISSUE THREAD

**Issue by tjhance** [verus-lang/verus#298]
This code, when verified with `--expand-errors`,

```rust
use builtin_macros::*;
use builtin::*;
mod pervasive;
use pervasive::*;
use pervasive::map::*;

verus!{

spec fn stuff(a: bool, b: bool, c: bool) -> bool {
    &&& a
    &&& b
    &&& c
}

proof fn foo() {
    assert(stuff(false, true, true));
}


fn main() {

}

}
```

gives a panic:

```rust
thread 'rustc' panicked at 'internal error: attempt to split non-boolean expression', vir/src/split_expression.rs:255:13
stack backtrace:
   0: std::panicking::begin_panic
             at /Users/tjhance/verus/rust/library/std/src/panicking.rs:525:12
   1: vir::split_expression::split_expr
             at ./vir/src/split_expression.rs:255:13
   2: vir::split_expression::split_expr
             at ./vir/src/split_expression.rs:399:17
   3: vir::split_expression::split_expr
             at ./vir/src/split_expression.rs:266:31
   4: vir::split_expression::split_expr
             at ./vir/src/split_expression.rs:266:31
   5: vir::split_expression::split_expr
             at ./vir/src/split_expression.rs:357:28
   6: vir::split_expression::visit_split_stm
             at ./vir/src/split_expression.rs:547:35
   7: vir::split_expression::all_split_exp::{{closure}}
             at ./vir/src/split_expression.rs:604:35
   8: vir::sst_visitor::map_shallow_stm
             at ./vir/src/sst_visitor.rs:640:27
   9: vir::split_expression::all_split_exp
             at ./vir/src/split_expression.rs:604:5
  10: vir::ast_to_sst::State::finalize_stm
             at ./vir/src/ast_to_sst.rs:279:13
  11: vir::func_to_air::func_def_to_air
             at ./vir/src/func_to_air.rs:735:23
  12: rust_verify::verifier::Verifier::verify_module::{{closure}}
             at ./rust_verify/src/verifier.rs:971:58
  13: rust_verify::verifier::Verifier::verify_module
             at ./rust_verify/src/verifier.rs:1058:28
```

cc @channy412

**Comment by channy412** [comment]
https://github.com/verus-lang/verus/commit/06e1f93a29859e0cfc8c4468014fdd8863f44cf1 fixes this issue.
This panic was due to a "boxed" boolean type, which should be available to split logic.
