### ISSUE TITLE
Panic regarding use of undeclared function

### ISSUE THREAD

**Issue by jaylorch** [verus-lang/verus#610]
If you try to verify the following code:
```
    pub trait T {
        type Y;
    }

    pub struct S<A> where A: T {
        y: A::Y
    }
```
Verus panics. Here's its full-backtrace output:
```
thread 'rustc' panicked at 'internal error: ill-typed AIR code: error 'error 'error 'use of undeclared function proj%main!T./Y' in expression '(proj%main!T./Y A& A&.)'' in expression '(has_type y@ (proj%main!T./Y A& A&.))'' in expression '(=>
 (has_type y@ (proj%main!T./Y A& A&.))
 (has_type (Poly%main!S. (main!S./S y@)) (TYPE%main!S. A&))
)'', rust_verify/src/verifier.rs:233:17
stack backtrace:
   0:     0x7fd40b36159a - std::backtrace_rs::backtrace::libunwind::trace::h595f06c70adcc478
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7fd40b36159a - std::backtrace_rs::backtrace::trace_unsynchronized::h177a0149c76cdde9
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7fd40b36159a - std::sys_common::backtrace::_print_fmt::hc0701fd2c3530c58
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x7fd40b36159a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd4cd115d8750fd6c
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7fd40b3c339e - core::fmt::write::h93e2f5923c7eca08
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/fmt/mod.rs:1213:17
   5:     0x7fd40b351be5 - std::io::Write::write_fmt::h8162dbb45f0b9e62
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/io/mod.rs:1682:15
   6:     0x7fd40b361365 - std::sys_common::backtrace::_print::h1835ef8a8f9066da
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x7fd40b361365 - std::sys_common::backtrace::print::hcb5e6388b9235f41
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x7fd40b36412f - std::panicking::default_hook::{{closure}}::h9c084969ccf9a722
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:267:22
   9:     0x7fd40b363e6b - std::panicking::default_hook::h68fa2ba3c3c6c12f
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:286:9
  10:     0x7fd40b364949 - std::panicking::rust_panic_with_hook::h8d5c434518ef298c
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:688:13
  11:     0x7fd40b3646e9 - std::panicking::begin_panic_handler::{{closure}}::hf33414f5dabf6faf
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:579:13
  12:     0x7fd40b361a4c - std::sys_common::backtrace::__rust_end_short_backtrace::hc50389427413bb75
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/sys_common/backtrace.rs:137:18
  13:     0x7fd40b3643f2 - rust_begin_unwind
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:575:5
  14:     0x7fd40b3bfd43 - core::panicking::panic_fmt::h2de7a7938f816de8
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/panicking.rs:64:14
  15:     0x563a8c7fb85e - rust_verify::verifier::Verifier::check_internal_result::h54dfb27e3cc54f56
  16:     0x563a8c7fc7d4 - rust_verify::verifier::Verifier::run_commands::h161397bf187b5032
  17:     0x563a8c7fef44 - rust_verify::verifier::Verifier::verify_module::hc6b60623b9ed370d
  18:     0x563a8c8062da - rust_verify::verifier::Verifier::verify_crate::h28367e37c28a89cd
  19:     0x563a8c8d37e1 - verus_rustc_interface::passes::QueryContext::enter::hf060498564a015b6
  20:     0x563a8c809815 - <rust_verify::verifier::VerifierCallbacksEraseMacro as verus_rustc_driver::Callbacks>::after_expansion::h4580e795c27adae7
  21:     0x563a8c9ab770 - verus_rustc_interface::queries::<impl verus_rustc_interface::interface::Compiler>::enter::hd8ac72a3c8c0c46a
  22:     0x563a8c9c966a - rustc_span::with_source_map::h2122596747b16d25
  23:     0x563a8c9705b5 - scoped_tls::ScopedKey<T>::set::h86c638eb05fc5fae
  24:     0x563a8c963870 - std::sys_common::backtrace::__rust_begin_short_backtrace::h549de802b86bff6b
  25:     0x563a8c95464d - core::ops::function::FnOnce::call_once{{vtable.shim}}::hc33b409d9eaebf7a
  26:     0x7fd40b36e823 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h1c0f3664d7ced314
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/alloc/src/boxed.rs:1988:9
  27:     0x7fd40b36e823 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h67647c21c6c4968a
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/alloc/src/boxed.rs:1988:9
  28:     0x7fd40b36e823 - std::sys::unix::thread::Thread::new::thread_start::h355d348ba593a22c
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/sys/unix/thread.rs:108:17
  29:     0x7fd40b218609 - start_thread
  30:     0x7fd40afec133 - clone
  31:                0x0 - <unknown>
```

**Comment by jaylorch** [comment]
I see this has been fixed, so I'll close the issue.
