### ISSUE TITLE
Panic at PredicateKind::TypeOutlives

### ISSUE THREAD

**Issue by jaylorch** [verus-lang/verus#613]
The following code:
```
    pub trait T {
        type Y;
    }

    pub struct S<'a, X> where X: T {
        r: &'a X::Y
    }
```
triggers the following panic:
```
thread 'rustc' panicked at 'PredicateKind::TypeOutlives', rust_verify/src/lifetime_generate.rs:1427:26
stack backtrace:
   0:     0x7f8b33ae259a - std::backtrace_rs::backtrace::libunwind::trace::h595f06c70adcc478
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f8b33ae259a - std::backtrace_rs::backtrace::trace_unsynchronized::h177a0149c76cdde9
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f8b33ae259a - std::sys_common::backtrace::_print_fmt::hc0701fd2c3530c58
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x7f8b33ae259a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd4cd115d8750fd6c
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f8b33b4439e - core::fmt::write::h93e2f5923c7eca08
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/fmt/mod.rs:1213:17
   5:     0x7f8b33ad2be5 - std::io::Write::write_fmt::h8162dbb45f0b9e62
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/io/mod.rs:1682:15
   6:     0x7f8b33ae2365 - std::sys_common::backtrace::_print::h1835ef8a8f9066da
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x7f8b33ae2365 - std::sys_common::backtrace::print::hcb5e6388b9235f41
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x7f8b33ae512f - std::panicking::default_hook::{{closure}}::h9c084969ccf9a722
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:267:22
   9:     0x7f8b33ae4e6b - std::panicking::default_hook::h68fa2ba3c3c6c12f
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:286:9
  10:     0x7f8b33ae5949 - std::panicking::rust_panic_with_hook::h8d5c434518ef298c
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:688:13
  11:     0x560c6e573bfa - std::panicking::begin_panic::{{closure}}::hd17c6ac66181ebcd
  12:     0x560c6e57327c - std::sys_common::backtrace::__rust_end_short_backtrace::h0bc55887e0d7977e
  13:     0x560c6e4e93da - std::panicking::begin_panic::hd34979d30eb49893
  14:     0x560c6e568372 - rust_verify::lifetime_generate::erase_mir_generics::h4ee5345f555f141f
  15:     0x560c6e56a5e1 - rust_verify::lifetime_generate::erase_datatype::h91cd52af4531f9f4
  16:     0x560c6e570fab - rust_verify::lifetime_generate::gen_check_tracked_lifetimes::hc04f48b7b57504cf
  17:     0x560c6e6379ff - rust_verify::lifetime::check_tracked_lifetimes::h08b897081ed312cc
  18:     0x560c6e61c63e - verus_rustc_interface::passes::QueryContext::enter::hf060498564a015b6
  19:     0x560c6e551aa5 - <rust_verify::verifier::VerifierCallbacksEraseMacro as verus_rustc_driver::Callbacks>::after_expansion::h4580e795c27adae7
  20:     0x560c6e6f6950 - verus_rustc_interface::queries::<impl verus_rustc_interface::interface::Compiler>::enter::hd8ac72a3c8c0c46a
  21:     0x560c6e71484a - rustc_span::with_source_map::h2122596747b16d25
  22:     0x560c6e6bb795 - scoped_tls::ScopedKey<T>::set::h86c638eb05fc5fae
  23:     0x560c6e6aea50 - std::sys_common::backtrace::__rust_begin_short_backtrace::h549de802b86bff6b
  24:     0x560c6e69f82d - core::ops::function::FnOnce::call_once{{vtable.shim}}::hc33b409d9eaebf7a
  25:     0x7f8b33aef823 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h1c0f3664d7ced314
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/alloc/src/boxed.rs:1988:9
  26:     0x7f8b33aef823 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h67647c21c6c4968a
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/alloc/src/boxed.rs:1988:9
  27:     0x7f8b33aef823 - std::sys::unix::thread::Thread::new::thread_start::h355d348ba593a22c
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/sys/unix/thread.rs:108:17
  28:     0x7f8b33999609 - start_thread
  29:     0x7f8b3376d133 - clone
  30:                0x0 - <unknown>
```

**Comment by jaylorch** [comment]
This code is very similar to that of issue #610 but the panic has a very different error message, so I put it as a separate issue even though the underlying cause may be the same.

**Comment by jaylorch** [comment]
I see this has been fixed, so I'll close the issue.
