### ISSUE TITLE
Panic, in presence of `Option` and traits

### ISSUE THREAD

**Issue by jaybosamiya** [verus-lang/verus#662]
```rust
use vstd::prelude::*;
fn main() {}

verus! {
  trait Foo : Sized {
    fn foo()->(e : Option<Self>);
  }
  struct Wrap<B>(B);
  impl<B : Foo> Wrap<B> {
    fn foo()->(e : Option<Self>) {
      Some((Wrap(B::foo()?)))
    }
  }
}
```

Minimized from https://github.com/verus-lang/verus-systems-code/tree/0eed32d9fc68bf06f034fed2837f217821282524/ironfleet-comparison/ironsht/src (note: this is currently a blocker on ironsht)

Minimization was originally performed using the [minimizers](https://github.com/verus-lang/verus/tree/main/source/tools/minimizers), down to a ~400 byte minimization, after which we manually cleaned it up a little bit while trying to understand what is going on (thus the nicer names of `Wrap`, `Foo`, etc.)

## Verus version

```console
Verus
  Platform: linux_x86_64
  Version: 0.2023.06.30.94d9ae3
  Profile: release
```

## Panic

```console
$ verus ./foo.rs
thread 'rustc' panicked at 'range end index 1 out of range for slice of length 0', compiler/rustc_middle/src/ty/sty.rs:856:55
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

## Backtrace

<details><summary>Click to expand</summary>

```console
$ RUST_BACKTRACE=1 verus ./foo.rs
thread 'rustc' panicked at 'range end index 1 out of range for slice of length 0', compiler/rustc_middle/src/ty/sty.rs:856:55
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::slice::index::slice_end_index_len_fail_rt
   3: core::slice::index::slice_end_index_len_fail
   4: <rustc_middle::ty::sty::TraitRef>::from_method
   5: rustc_ty_utils::instance::inner_resolve_instance
   6: rustc_ty_utils::instance::resolve_instance
   7: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::queries::resolve_instance, rustc_query_impl::plumbing::QueryCtxt>
   8: rustc_query_system::query::plumbing::get_query::<rustc_query_impl::queries::resolve_instance, rustc_query_impl::plumbing::QueryCtxt, rustc_middle::dep_graph::dep_node::DepKind>
   9: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::resolve_instance
  10: <rustc_middle::ty::instance::Instance>::resolve_opt_const_arg
  11: <rustc_middle::ty::instance::Instance>::resolve
  12: rust_verify::fn_call_to_vir::fn_call_to_vir
  13: rust_verify::rust_to_vir_expr::expr_to_vir_innermost
  14: rust_verify::rust_to_vir_expr::expr_to_vir_inner
  15: rust_verify::rust_to_vir_expr::expr_to_vir
  16: rust_verify::rust_to_vir_expr::expr_to_vir_innermost
  17: rust_verify::rust_to_vir_expr::expr_to_vir_inner
  18: rust_verify::rust_to_vir_expr::expr_to_vir
  19: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold
  20: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
  21: core::iter::adapters::try_process
  22: rust_verify::rust_to_vir_expr::expr_tuple_datatype_ctor_to_vir
  23: rust_verify::rust_to_vir_expr::expr_to_vir_innermost
  24: rust_verify::rust_to_vir_expr::expr_to_vir_inner
  25: rust_verify::rust_to_vir_expr::expr_to_vir
  26: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold
  27: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
  28: core::iter::adapters::try_process
  29: rust_verify::rust_to_vir_expr::expr_tuple_datatype_ctor_to_vir
  30: rust_verify::rust_to_vir_expr::expr_to_vir_innermost
  31: rust_verify::rust_to_vir_expr::expr_to_vir_inner
  32: rust_verify::rust_to_vir_expr::expr_to_vir
  33: rust_verify::rust_to_vir_expr::block_to_vir
  34: rust_verify::rust_to_vir_expr::expr_to_vir_innermost
  35: rust_verify::rust_to_vir_expr::expr_to_vir_inner
  36: rust_verify::rust_to_vir_expr::expr_to_vir
  37: rust_verify::rust_to_vir_func::check_item_fn
  38: rust_verify::rust_to_vir::check_item
  39: rust_verify::rust_to_vir::crate_to_vir
  40: rust_verify::verifier::Verifier::construct_vir_crate
  41: verus_rustc_interface::passes::QueryContext::enter
  42: <rust_verify::verifier::VerifierCallbacksEraseMacro as verus_rustc_driver::Callbacks>::after_expansion
  43: verus_rustc_interface::queries::<impl verus_rustc_interface::interface::Compiler>::enter
  44: rustc_span::with_source_map
  45: scoped_tls::ScopedKey<T>::set
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

</details>

**Comment by jaybosamiya** [comment]
Further minimized:
```rust
    pub fn foo(n: Option<bool>) -> Option<bool>
    {
        Some(n?)
    }
```

**Comment by tjhance** [comment]
There's now a sane 'not supported' error message if the user uses a `?`.

**Comment by jaybosamiya** [comment]
Thanks, closing the issue since there is no longer a panic for it.
