### ISSUE TITLE
Panic when using associated type in exec function

### ISSUE THREAD

**Issue by jaybosamiya** [verus-lang/verus#724]
```rust
use vstd::prelude::*;
fn main() {}
verus! {

  // Panic
  exec fn foo<T: View>(c : T::V)
  {
  }

  // No panic
  proof fn bar<T: View>(c : T::V)
  {
  }

}
```
Notice that `foo` panics, but `bar` doesn't.

```console
$ verus foo.rs
thread 'rustc' panicked at 'assertion failed: state.trait_decl_set.contains(&trait_path_vir)', rust_verify/src/lifetime_generate.rs:409:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

## Backtrace

<details><summary>Click to expand</summary>

```console
$ RUST_BACKTRACE=1 verus foo.rs
thread 'rustc' panicked at 'assertion failed: state.trait_decl_set.contains(&trait_path_vir)', rust_verify/src/lifetime_generate.rs:409:21
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic
   3: rust_verify::lifetime_generate::erase_ty
   4: rust_verify::lifetime_generate::erase_fn_common
   5: rust_verify::lifetime_generate::gen_check_tracked_lifetimes
   6: rust_verify::lifetime::check_tracked_lifetimes
   7: verus_rustc_interface::passes::QueryContext::enter
   8: <rust_verify::verifier::VerifierCallbacksEraseMacro as verus_rustc_driver::Callbacks>::after_expansion
   9: verus_rustc_interface::queries::<impl verus_rustc_interface::interface::Compiler>::enter
  10: rustc_span::with_source_map
  11: scoped_tls::ScopedKey<T>::set
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

</details>

---

Found when diagnosing and minimizing equivalent panic found by @tracyee

---

Tested on
```
Verus
  Version: 0.2023.07.25.095d336
  Profile: release
  Platform: macos_aarch64
  Toolchain: 1.68.0-aarch64-apple-darwin
```

**Comment by Tracyee** [comment]
It does not panic if we use a self-defined trait:

```rust
use vstd::prelude::*;
fn main() {}
verus! {

  trait Miew {
    type M;
    spec fn miew(&self) -> Self::M;
  }

  // Panic
  exec fn foo<T: Miew>(c : T::M)
  {
  }

  // No panic
  proof fn bar<T: Miew>(c : T::M)
  {
  }

}
```

```
verification results:: 3 verified, 0 errors
```

**Comment by utaal** [comment]
Fixed by https://github.com/verus-lang/verus/commit/d8ae36362248ad5eb4c22094297088573fc6022f
