### ISSUE TITLE
Panic with associated type bound and closure (?)

### ISSUE THREAD

**Issue by utaal** [verus-lang/verus#910]
```rust
trait T {
    type X;
}

struct L<D: T> {
    x: D::X,
}

spec fn f<DT: T>(l: Map<nat, L<DT>>) -> Seq<DT::X> {
    Seq::new(1, |i: int| l[i as nat].x)
}
```

panics:

```
thread '<unnamed>' panicked at vir/src/sst_to_air.rs:984:41:
Box
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at rust_verify/src/verifier.rs:1823:29:
worker thread panicked
```

**Comment by utaal** [comment]
Minimized:
```rust
trait T {
    type X;
}

struct L<D: T> {
    x: D::X,
}

spec fn f<DT: T>(l: L<DT>) -> FnSpec(L<DT>)->DT::X {
    |ll: L<DT>| ll.x
}
```
