### ISSUE TITLE
Panic when selecting a trigger that involves a closure argument

### ISSUE THREAD

**Issue by matthias-brun** [verus-lang/verus#946]
I don't know if such a trigger would even be reasonable but Verus probably shouldn't panic.

```rust
use vstd::prelude::*;

verus!{

fn main() { }

proof fn x()
    ensures forall|P: FnSpec(nat) -> bool| Set::new(|i: nat| false && #[trigger] P(i)).finite(),
{}
}
```

```
ξ verus-release /st/verus/test.rs
thread '<unnamed>' panicked at rust_verify/src/verifier.rs:506:17:
internal error: ill-typed AIR code: error 'use of undeclared variable i~29$' in expression 'i~29$'
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at rust_verify/src/verifier.rs:332:17:
dropped, expected call to `into_inner` instead
stack backtrace:
[ ... backtrace omitted ... ]
thread '<unnamed>' panicked at library/core/src/panicking.rs:126:5:
panic in a function that cannot unwind
stack backtrace:
[ ... backtrace omitted ... ]
thread caused non-unwinding panic. aborting.
zsh: abort (core dumped)  /st/verus/verus/source/target-verus/release/verus /st/verus/test.rs
```

**Comment by tjhance** [comment]
this has been fixed, it's now a warning and a "Could not automatically infer triggers for this quantifier."
