### ISSUE TITLE
trait variable renaming in --expand-errors

### ISSUE THREAD

**Issue by jonhnet** [verus-lang/verus#952]
[2024-01-02-15-38-58.zip](https://github.com/verus-lang/verus/files/13814645/2024-01-02-15-38-58.zip)

**Comment by jonhnet** [comment]
[2024-01-02-15-42-42.zip](https://github.com/verus-lang/verus/files/13814659/2024-01-02-15-42-42.zip)

Actually, here's a better recording, with some cruft removed. Line 135 is the difference between crash and no crash.

**Comment by jaybosamiya** [comment]
From a quick look, this might have something to do with `--expand-errors` (running without it, it at least doesn't crash).

Linking as possibly relevant: #859 (even though it is a different panic happening, it involves traits, AIR, and `--expand-errors`)

**Comment by jonhnet** [comment]
Ah! Thank you, that can unblock me! Much appreciated.

**Comment by jonhnet** [comment]
Rats. In my current situation (recording attached), the bug still happens even with --expand-errors and --multiple-errors removed:

[2024-01-06-07-47-55.zip](https://github.com/verus-lang/verus/files/13850233/2024-01-06-07-47-55.zip)

**Comment by tjhance** [comment]
The issue is that Verus does not support defaults on generic params. This is what the error message should look like when the panic is corrected:

```
error: The verifier does not yet support the following Rust feature: this kind of generic param
  --> marshalling/IntegerMarshalling_v.rs:18:27
   |
18 | pub trait NativePackedInt<DV=int> {
   |                           ^^^^^^
```

**Comment by tjhance** [comment]
By the way, we should probably just support defaults. I don't think we'd even need to do anything since we get all the information post-typechecking

**Comment by jonhnet** [comment]
Oh rats! That default was a workaround for not having defaults at the associated-type level. I thought it was working, but perhaps I just hadn't gotten far enough to see it fail.

**Comment by jaybosamiya** [comment]
Running the automatic minimizer, it seems like there is indeed a scenario where this particular error happens only for `--expand-errors` but not without it.

The minimized code:
```rust
use vstd::prelude::*;
verus! {

struct C;

trait D<E> {
    spec fn f(&self) -> bool;
    
    spec fn g(&self, data: Seq<u8>) -> bool;
    
    fn h(&self, i: C, data: &Vec<u8>) -> bool;
    
    spec fn j(&self, k: &E) -> bool;
    
    spec fn l(&self, k: &E) -> u64;
    
    fn m(&self, k: &E) -> (p: u64)
        ensures
            p == self.l(k),
    ;
}

trait N {
    type O;
    
    fn m() -> u64;
}

impl<E> D<E::O> for E where E: N {
    spec fn f(&self) -> bool;
    
    spec fn g(&self, data: Seq<u8>) -> bool;
    
    fn h(&self, i: C, data: &Vec<u8>) -> bool {
        true
    }
    
    spec fn j(&self, k: &E::O) -> bool;
    
    spec fn l(&self, k: &E::O) -> u64;
    
    fn m(&self, k: &E::O) -> u64 {
        E::m()
    }
}

} // verus!
fn main() {}
```

Execution:

```console
$ verus --version
Verus
  Version: 0.2023.12.29.3ac6c83
  Profile: release
  Platform: macos_aarch64
  Toolchain: 1.73.0-aarch64-apple-darwin
$ verus foo.rs
error: postcondition not satisfied
  --> foo.rs:42:34
   |
19 |               p == self.l(k),
   |               -------------- failed this postcondition
...
42 |       fn m(&self, k: &E::O) -> u64 {
   |  __________________________________^
43 | |         E::m()
44 | |     }
   | |_____^ at the end of the function body

error: aborting due to previous error

verification results:: 1 verified, 1 errors
$ verus --expand-errors foo.rs
thread '<unnamed>' panicked at vir/src/ast_to_sst.rs:160:21:
internal error: variable not in rename_map: p~12
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at rust_verify/src/verifier.rs:332:17:
dropped, expected call to `into_inner` instead
stack backtrace:
   0:        0x10573af10 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h6d4268b2ed62fb94
   1:        0x10578ed2c - core::fmt::write::h5d55d44549819258
   2:        0x105730940 - std::io::Write::write_fmt::hc515897f91abd6cf
   3:        0x10573ad50 - std::sys_common::backtrace::print::h2c300c1ebedfc73c
   4:        0x10573d9a8 - std::panicking::default_hook::{{closure}}::h0aa9be5c44269370
   5:        0x10573d6d4 - std::panicking::default_hook::h2c0ef097934ee9e6
   6:        0x10573e008 - std::panicking::rust_panic_with_hook::h84c8637cb6e56008
   7:        0x1040adef4 - std::panicking::begin_panic::{{closure}}::h56a458e20ce175f4
   8:        0x1040ac488 - std::sys_common::backtrace::__rust_end_short_backtrace::h0d8d3be363e444be
   9:        0x104589b10 - std::panicking::begin_panic::h013ba2e310e5c467
  10:        0x1040b0afc - core::ptr::drop_in_place<core::cell::RefCell<core::option::Option<rust_verify::verifier::util::PanicOnDropVec<(alloc::sync::Arc<vir::messages::MessageX>,air::messages::MessageLevel)>>>>::h35fcd62946510b4d
  11:        0x1040cb148 - rust_verify::verifier::Verifier::verify_bucket::h6cda8f276c956f6b
  12:        0x1040cb670 - rust_verify::verifier::Verifier::verify_bucket_outer::h71957d724b5ffa26
  13:        0x10410bdf4 - std::panicking::try::h2d55a092a8099a5b
  14:        0x1040ac4e0 - std::sys_common::backtrace::__rust_begin_short_backtrace::h6b169b862ec72a17
  15:        0x10420c004 - core::ops::function::FnOnce::call_once{{vtable.shim}}::hb52382cb1d921412
  16:        0x105746da4 - std::sys::unix::thread::Thread::new::thread_start::h6244aa8f646b01ac
  17:        0x193f4026c - __pthread_deallocate
thread '<unnamed>' panicked at library/core/src/panicking.rs:126:5:
panic in a function that cannot unwind
stack backtrace:
   0:        0x10573af10 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h6d4268b2ed62fb94
   1:        0x10578ed2c - core::fmt::write::h5d55d44549819258
   2:        0x105730940 - std::io::Write::write_fmt::hc515897f91abd6cf
   3:        0x10573ad50 - std::sys_common::backtrace::print::h2c300c1ebedfc73c
   4:        0x10573d9a8 - std::panicking::default_hook::{{closure}}::h0aa9be5c44269370
   5:        0x10573d6d4 - std::panicking::default_hook::h2c0ef097934ee9e6
   6:        0x10573e008 - std::panicking::rust_panic_with_hook::h84c8637cb6e56008
   7:        0x10573ded8 - std::panicking::begin_panic_handler::{{closure}}::h25482adda06c7b7f
   8:        0x10573b39c - std::sys_common::backtrace::__rust_end_short_backtrace::h0c6f3beb22324a29
   9:        0x10573dc78 - _rust_begin_unwind
  10:        0x1057ba258 - core::panicking::panic_nounwind_fmt::ha4f6bbf8fe9fb5ae
  11:        0x1057ba2d4 - core::panicking::panic_nounwind::ha756411eedbc9594
  12:        0x1057ba3d0 - core::panicking::panic_cannot_unwind::h496677c8c27b4397
  13:        0x1040cb1c0 - rust_verify::verifier::Verifier::verify_bucket::h6cda8f276c956f6b
  14:        0x1040cb670 - rust_verify::verifier::Verifier::verify_bucket_outer::h71957d724b5ffa26
  15:        0x10410bdf4 - std::panicking::try::h2d55a092a8099a5b
  16:        0x1040ac4e0 - std::sys_common::backtrace::__rust_begin_short_backtrace::h6b169b862ec72a17
  17:        0x10420c004 - core::ops::function::FnOnce::call_once{{vtable.shim}}::hb52382cb1d921412
  18:        0x105746da4 - std::sys::unix::thread::Thread::new::thread_start::h6244aa8f646b01ac
  19:        0x193f4026c - __pthread_deallocate
thread caused non-unwinding panic. aborting.
[1]    94410 abort      verus --expand-errors foo.rs
```

**Comment by tjhance** [comment]
Pretty sure that has to do with the fact that return value 'p' is named in the trait method but not the impl method. This was fixed recently for the common case, so there must be a similar issue in --expand-errors.

**Comment by jonhnet** [comment]
For triage purposes: @utaal has pointed out that I didn't even want a default type here anyway, so this issue is no longer blocking me. Thank you @jaybosamiya and @tjhance for investigating.

**Comment by tjhance** [comment]
Seems this was fixed along with https://github.com/verus-lang/verus/issues/859

I added a test in 7668a1bacd0d4d4f3f89bdb4e7fdb67d279207b5
